// ============================================================
// COMPANY NAME MAPPING
// ============================================================
export const COMPANY_NAMES: Record<string, string> = {
  // ETFs
  'SPY': 'SPDR S&P 500 ETF Trust',
  'QQQ': 'Invesco QQQ Trust',
  'IWM': 'iShares Russell 2000 ETF',
  'DIA': 'SPDR Dow Jones Industrial Average ETF',
  'VTI': 'Vanguard Total Stock Market ETF',
  'XLE': 'Energy Select Sector SPDR Fund',
  'VOO': 'Vanguard S&P 500 ETF',
  'VEA': 'Vanguard FTSE Developed Markets ETF',
  'VWO': 'Vanguard FTSE Emerging Markets ETF',
  'AGG': 'iShares Core U.S. Aggregate Bond ETF',
  'BND': 'Vanguard Total Bond Market ETF',
  'XLF': 'Financial Select Sector SPDR Fund',
  'XLK': 'Technology Select Sector SPDR Fund',
  'XLV': 'Health Care Select Sector SPDR Fund',
  'XLI': 'Industrial Select Sector SPDR Fund',
  
  // Technology
  'AAPL': 'Apple Inc.',
  'MSFT': 'Microsoft Corporation',
  'GOOGL': 'Alphabet Inc.',
  'AMZN': 'Amazon.com Inc.',
  'META': 'Meta Platforms Inc.',
  'NVDA': 'NVIDIA Corporation',
  'TSLA': 'Tesla Inc.',
  'ORCL': 'Oracle Corporation',
  'CRM': 'Salesforce Inc.',
  'ADBE': 'Adobe Inc.',
  'ACN': 'Accenture plc',
  'NOW': 'ServiceNow Inc.',
  'INTU': 'Intuit Inc.',
  
  // Semiconductors
  'AMD': 'Advanced Micro Devices Inc.',
  'INTC': 'Intel Corporation',
  'AVGO': 'Broadcom Inc.',
  'TSM': 'Taiwan Semiconductor Manufacturing',
  'QCOM': 'QUALCOMM Incorporated',
  'TXN': 'Texas Instruments Incorporated',
  'AMAT': 'Applied Materials Inc.',
  'LRCX': 'Lam Research Corporation',
  'KLAC': 'KLA Corporation',
  'ADI': 'Analog Devices Inc.',
  'MRVL': 'Marvell Technology Inc.',
  'NXPI': 'NXP Semiconductors N.V.',
  'MCHP': 'Microchip Technology Incorporated',
  'ON': 'ON Semiconductor Corporation',
  
  // Finance
  'JPM': 'JPMorgan Chase & Co.',
  'BAC': 'Bank of America Corporation',
  'WFC': 'Wells Fargo & Company',
  'MS': 'Morgan Stanley',
  'GS': 'The Goldman Sachs Group Inc.',
  'C': 'Citigroup Inc.',
  'BX': 'Blackstone Inc.',
  'SCHW': 'The Charles Schwab Corporation',
  'AXP': 'American Express Company',
  'USB': 'U.S. Bancorp',
  'PNC': 'The PNC Financial Services Group',
  'TFC': 'Truist Financial Corporation',
  'BLK': 'BlackRock Inc.',
  'COF': 'Capital One Financial Corporation',
  'CME': 'CME Group Inc.',
  'BRK.B': 'Berkshire Hathaway Inc.',
  'V': 'Visa Inc.',
  'MA': 'Mastercard Incorporated',
  
  // Healthcare
  'UNH': 'UnitedHealth Group Incorporated',
  'JNJ': 'Johnson & Johnson',
  'LLY': 'Eli Lilly and Company',
  'ABBV': 'AbbVie Inc.',
  'MRK': 'Merck & Co. Inc.',
  'TMO': 'Thermo Fisher Scientific Inc.',
  'ABT': 'Abbott Laboratories',
  'DHR': 'Danaher Corporation',
  'PFE': 'Pfizer Inc.',
  'BMY': 'Bristol-Myers Squibb Company',
  'AMGN': 'Amgen Inc.',
  'GILD': 'Gilead Sciences Inc.',
  'CVS': 'CVS Health Corporation',
  'CI': 'The Cigna Group',
  'HCA': 'HCA Healthcare Inc.',
  
  // Consumer Discretionary
  'HD': 'The Home Depot Inc.',
  'MCD': "McDonald's Corporation",
  'NKE': 'NIKE Inc.',
  'SBUX': 'Starbucks Corporation',
  'LOW': "Lowe's Companies Inc.",
  'TJX': 'The TJX Companies Inc.',
  'BKNG': 'Booking Holdings Inc.',
  'MAR': 'Marriott International Inc.',
  'CMG': 'Chipotle Mexican Grill Inc.',
  'ABNB': 'Airbnb Inc.',
  'GM': 'General Motors Company',
  'F': 'Ford Motor Company',
  'ORLY': "O'Reilly Automotive Inc.",
  
  // Consumer Staples
  'WMT': 'Walmart Inc.',
  'COST': 'Costco Wholesale Corporation',
  'PG': 'The Procter & Gamble Company',
  'KO': 'The Coca-Cola Company',
  'PEP': 'PepsiCo Inc.',
  'PM': 'Philip Morris International Inc.',
  'MO': 'Altria Group Inc.',
  'CL': 'Colgate-Palmolive Company',
  'MDLZ': 'Mondelēz International Inc.',
  'KMB': 'Kimberly-Clark Corporation',
  'GIS': 'General Mills Inc.',
  'STZ': 'Constellation Brands Inc.',
  'HSY': 'The Hershey Company',
  'K': 'Kellanova',
  'CPB': 'Campbell Soup Company',
  
  // Energy
  'XOM': 'Exxon Mobil Corporation',
  'CVX': 'Chevron Corporation',
  'COP': 'ConocoPhillips',
  'SLB': 'SLB',
  'EOG': 'EOG Resources Inc.',
  'MPC': 'Marathon Petroleum Corporation',
  'PSX': 'Phillips 66',
  'VLO': 'Valero Energy Corporation',
  'OXY': 'Occidental Petroleum Corporation',
  'HAL': 'Halliburton Company',
  'KMI': 'Kinder Morgan Inc.',
  'WMB': 'The Williams Companies Inc.',
  'DVN': 'Devon Energy Corporation',
  'HES': 'Hess Corporation',
  'BKR': 'Baker Hughes Company',
  
  // Industrials
  'CAT': 'Caterpillar Inc.',
  'BA': 'The Boeing Company',
  'GE': 'General Electric Company',
  'UPS': 'United Parcel Service Inc.',
  'HON': 'Honeywell International Inc.',
  'UNP': 'Union Pacific Corporation',
  'RTX': 'RTX Corporation',
  'LMT': 'Lockheed Martin Corporation',
  'DE': 'Deere & Company',
  'MMM': '3M Company',
  'EMR': 'Emerson Electric Co.',
  'ETN': 'Eaton Corporation plc',
  'ITW': 'Illinois Tool Works Inc.',
  'CSX': 'CSX Corporation',
  'NSC': 'Norfolk Southern Corporation',
  
  // Communication Services
  'NFLX': 'Netflix Inc.',
  'DIS': 'The Walt Disney Company',
  'CMCSA': 'Comcast Corporation',
  'T': 'AT&T Inc.',
  'VZ': 'Verizon Communications Inc.',
  'TMUS': 'T-Mobile US Inc.',
  'CHTR': 'Charter Communications Inc.',
  'EA': 'Electronic Arts Inc.',
  'TTWO': 'Take-Two Interactive Software Inc.',
  'WBD': 'Warner Bros. Discovery Inc.',
  'PARA': 'Paramount Global',
  'FOXA': 'Fox Corporation',
  'MTCH': 'Match Group Inc.',
  
  // Real Estate
  'PLD': 'Prologis Inc.',
  'AMT': 'American Tower Corporation',
  'EQIX': 'Equinix Inc.',
  'PSA': 'Public Storage',
  'WELL': 'Welltower Inc.',
  'SPG': 'Simon Property Group Inc.',
  'DLR': 'Digital Realty Trust Inc.',
  'O': 'Realty Income Corporation',
  'CCI': 'Crown Castle Inc.',
  'VICI': 'VICI Properties Inc.',
  'AVB': 'AvalonBay Communities Inc.',
  'EQR': 'Equity Residential',
  'SBAC': 'SBA Communications Corporation',
  'WY': 'Weyerhaeuser Company',
  'ARE': 'Alexandria Real Estate Equities Inc.',
  
  // Utilities
  'NEE': 'NextEra Energy Inc.',
  'DUK': 'Duke Energy Corporation',
  'SO': 'The Southern Company',
  'D': 'Dominion Energy Inc.',
  'AEP': 'American Electric Power Company Inc.',
  'EXC': 'Exelon Corporation',
  'SRE': 'Sempra',
  'XEL': 'Xcel Energy Inc.',
  'ED': 'Consolidated Edison Inc.',
  'PEG': 'Public Service Enterprise Group Inc.',
  'EIX': 'Edison International',
  'WEC': 'WEC Energy Group Inc.',
  'ES': 'Eversource Energy',
  'AWK': 'American Water Works Company Inc.',
  'DTE': 'DTE Energy Company',
  
  // Materials
  'LIN': 'Linde plc',
  'APD': 'Air Products and Chemicals Inc.',
  'SHW': 'The Sherwin-Williams Company',
  'ECL': 'Ecolab Inc.',
  'DD': 'DuPont de Nemours Inc.',
  'NEM': 'Newmont Corporation',
  'FCX': 'Freeport-McMoRan Inc.',
  'NUE': 'Nucor Corporation',
  'DOW': 'Dow Inc.',
  'PPG': 'PPG Industries Inc.',
  'VMC': 'Vulcan Materials Company',
  'MLM': 'Martin Marietta Materials Inc.',
  'ALB': 'Albemarle Corporation',
  'CF': 'CF Industries Holdings Inc.',
  'MOS': 'The Mosaic Company',
};
